name: Checkov Scan

on:
  workflow_call:
    

jobs:
  checkov-scan:
    permissions: read-all  # Set the required permissions for this reusable workflow
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
