name: Checkov Scan

on:
  workflow_call:
    permissions:
      read-all: true  # Set the required permissions for this reusable workflow

jobs:
  checkov-scan:
    runs-on: ci-runner-dev-linux-sandbox

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
