name: Main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
      - name: Run Checkov Scan
        uses: checkov/./.github/workflows/checkov-scan.yml@main  # Call the reusable workflow
