name: Security Scans

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git Secrets
        run: |
          git secrets --register-raw-hashes
          git secrets --install

      - name: Run Git Secrets Scan
        id: git-secrets
        run: |
          git secrets --scan > git-secrets-results.txt || true
          cat git-secrets-results.txt
          if grep -q 'found' git-secrets-results.txt; then
            echo "Secrets detected!" >> $GITHUB_ENV
          fi

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov Scan
        id: checkov
        run: |
          checkov --directory . --quiet --output json --skip-check ${{ inputs.skip_checks }} > checkov-results.json
          cat checkov-results.json
          if grep -q '"result": "FAIL"' checkov-results.json; then
            echo "Critical security violations found!" >> $GITHUB_ENV
          fi

      - name: Report Results
        run: |
          if [ -n "$SECRETS_DETECTED" ]; then
            echo "Secrets were detected. Failing the Action."
            exit 1
          fi
          if grep -q '"result": "FAIL"' checkov-results.json; then
            echo "Checkov found critical violations. Failing the Action."
            exit 1
          fi
          echo "No issues found!"

      - name: Upload Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: security-scan-results
          path: |
            git-secrets-results.txt
            checkov-results.json